
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'

target 'tanzak' do

  # Required by RNFirebase
  pod 'RNFBApp', :path => '../node_modules/@react-native-firebase/app'
  pod 'RNFBMessaging', :path => '../node_modules/@react-native-firebase/messaging'
  pod 'RNNotifee', :path => '../node_modules/@notifee/react-native/'

  pod 'RNFastImage', :path => '../node_modules/react-native-fast-image/RNFastImage.podspec'

  pod 'ExpoKit',
    :git => "http://github.com/expo/expo.git",
    :tag => "ios/2.14.1",
    :subspecs => [
      "Core"
    ],
    :inhibit_warnings => true


  pod 'Google-Mobile-Ads-SDK'
  pod 'AppLovinSDK'
  pod 'AppLovinMediationGoogleAdapter'
  pod 'AppLovinMediationFacebookAdapter'

  pod 'react-native-appsflyer',
    :path => '../node_modules/react-native-appsflyer'

  # pod 'EXAdsAdMob',
  #   :path => "../node_modules/expo-ads-admob/ios"
  # pod 'EXSegment',
  #   :path => "../node_modules/expo-analytics-segment/ios"
  # pod 'EXAppAuth',
  #   :path => "../node_modules/expo-app-auth/ios"
  # pod 'EXAppLoaderProvider',
  #   :path => "../node_modules/expo-app-loader-provider/ios"
  # pod 'EXBackgroundFetch',
  #   :path => "../node_modules/expo-background-fetch/ios"
  # pod 'EXBarCodeScanner',
  #   :path => "../node_modules/expo-barcode-scanner/ios"
  # pod 'EXBarCodeScannerInterface',
  #   :path => "../node_modules/expo-barcode-scanner-interface/ios"
  # pod 'EXCameraInterface',
  #   :path => "../node_modules/expo-camera-interface/ios"
  # pod 'EXConstants',
  #   :path => "../node_modules/expo-constants/ios"
  # pod 'EXConstantsInterface',
  #   :path => "../node_modules/expo-constants-interface/ios"
  # pod 'EXCore',
  #   :path => "../node_modules/expo-core/ios"
  # pod 'EXErrors',
  #   :path => "../node_modules/expo-errors/ios"
  # pod 'EXFaceDetectorInterface',
  #   :path => "../node_modules/expo-face-detector-interface/ios"
  # pod 'EXFileSystem',
  #   :path => "../node_modules/expo-file-system/ios"
  # pod 'EXFileSystemInterface',
  #   :path => "../node_modules/expo-file-system-interface/ios"
  # pod 'EXFont',
  #   :path => "../node_modules/expo-font/ios"
  # pod 'EXFontInterface',
  #   :path => "../node_modules/expo-font-interface/ios"
  # pod 'EXGL',
  #   :path => "../node_modules/expo-gl/ios"
  # pod 'EXGL-CPP',
  #   :path => "../node_modules/expo-gl-cpp/cpp"
  # pod 'EXGoogleSignIn',
  #   :path => "../node_modules/expo-google-sign-in/ios"
  # pod 'EXImageLoaderInterface',
  #   :path => "../node_modules/expo-image-loader-interface/ios"
  # pod 'EXLocalAuthentication',
  #   :path => "../node_modules/expo-local-authentication/ios"
  # pod 'EXLocalization',
  #   :path => "../node_modules/expo-localization/ios"
  # pod 'EXLocation',
  #   :path => "../node_modules/expo-location/ios"
  # pod 'EXPermissions',
  #   :path => "../node_modules/expo-permissions/ios"
  # pod 'EXPermissionsInterface',
  #   :path => "../node_modules/expo-permissions-interface/ios"
  # pod 'EXPrint',
  #   :path => "../node_modules/expo-print/ios"
  # pod 'EXReactNativeAdapter',
  #   :path => "../node_modules/expo-react-native-adapter/ios"
  # pod 'EXSensors',
  #   :path => "../node_modules/expo-sensors/ios"
  # pod 'EXSensorsInterface',
  #   :path => "../node_modules/expo-sensors-interface/ios"
  # pod 'EXSMS',
  #   :path => "../node_modules/expo-sms/ios"
  # pod 'EXTaskManager',
  #   :path => "../node_modules/expo-task-manager/ios"
  # pod 'EXTaskManagerInterface',
  #   :path => "../node_modules/expo-task-manager-interface/ios"

  # UPDATE TO SDK 34
  # Install unimodules
  require_relative '../node_modules/react-native-unimodules/cocoapods.rb'
  use_unimodules!

  # pod 'React',
  #   :path => "../node_modules/react-native",
  #   :inhibit_warnings => true,
  #   :subspecs => [
  #     "Core",
  #     "ART",
  #     "RCTActionSheet",
  #     "RCTAnimation",
  #     "RCTGeolocation",
  #     "RCTImage",
  #     "RCTNetwork",
  #     "RCTText",
  #     "RCTVibration",
  #     "RCTWebSocket",
  #     "DevSupport",
  #     "CxxBridge"
  #   ]
  pod 'Yoga',
    :path => "../node_modules/react-native/ReactCommon/yoga",
    :inhibit_warnings => true
  pod 'DoubleConversion',
    :podspec => "../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec",
    :inhibit_warnings => true
  pod 'Folly',
    :podspec => "../node_modules/react-native/third-party-podspecs/Folly.podspec",
    :inhibit_warnings => true
  # pod 'glog',
  #   :podspec => "../node_modules/react-native/third-party-podspecs/glog.podspec",
  #   :inhibit_warnings => true
  require_relative '../node_modules/react-native/scripts/autolink-ios.rb'
  use_react_native!





  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  pod 'react-native-in-app-utils', :path => '../node_modules/react-native-in-app-utils'


  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'

  # Crash report
  pod 'RNFBCrashlytics', :path => '../node_modules/@react-native-firebase/crashlytics'

  pod 'react-native-tracking-transparency', :path => '../node_modules/react-native-tracking-transparency'


  post_install do |installer|

      ## Fix for XCode 12.5
      find_and_replace("../node_modules/react-native/React/CxxBridge/RCTCxxBridge.mm",
      "_initializeModules:(NSArray<id<RCTBridgeModule>> *)modules", "_initializeModules:(NSArray<Class> *)modules")
      find_and_replace("../node_modules/react-native/ReactCommon/turbomodule/core/platform/ios/RCTTurboModuleManager.mm",
      "RCTBridgeModuleNameForClass(module))", "RCTBridgeModuleNameForClass(Class(module)))")

    installer.pods_project.main_group.tab_width = '2';
    installer.pods_project.main_group.indent_width = '2';

    installer.target_installation_results.pod_target_installation_results
      .each do |pod_name, target_installation_result|

      if pod_name == 'ExpoKit'
        target_installation_result.native_target.build_configurations.each do |config|
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'EX_DETACHED=1'

          # Enable Google Maps support
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'HAVE_GOOGLE_MAPS=1'
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'HAVE_GOOGLE_MAPS_UTILS=1'
        end
      end
      if ['Amplitude-iOS','Analytics','AppAuth','Branch','CocoaLumberjack','FBSDKCoreKit','FBSDKLoginKit','FBSDKShareKit','GPUImage','JKBigInteger2'].include? pod_name
        target_installation_result.native_target.build_configurations.each do |config|
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
        end
      end

      # Can't specify this in the React podspec because we need to use those podspecs for detached
      # projects which don't reference ExponentCPP.
      if pod_name.start_with?('React')
        target_installation_result.native_target.build_configurations.each do |config|
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
          config.build_settings['HEADER_SEARCH_PATHS'] ||= ['$(inherited)']
        end
      end

      # Build React Native with RCT_DEV enabled and RCT_ENABLE_INSPECTOR and
      # RCT_ENABLE_PACKAGER_CONNECTION disabled
      next unless pod_name == 'React'
      target_installation_result.native_target.build_configurations.each do |config|
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'RCT_DEV=1'
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'RCT_ENABLE_INSPECTOR=0'
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'ENABLE_PACKAGER_CONNECTION=0'
      end
    end
  end
end
def find_and_replace(dir, findstr, replacestr)
  Dir[dir].each do |name|
      text = File.read(name)
      replace = text.gsub(findstr,replacestr)
      if text != replace
          puts "Fix: " + name
          File.open(name, "w") { |file| file.puts replace }
          STDOUT.flush
      end
  end
  Dir[dir + '*/'].each(&method(:find_and_replace))
end
